//
// Created by llogan on 7/25/24.
//

#ifndef CHIMAERA_INCLUDE_CHIMAERA_MONITOR_PREDICT_LOG_H_
#define CHIMAERA_INCLUDE_CHIMAERA_MONITOR_PREDICT_LOG_H_

namespace chi {

class PredictLog {};

}

#endif //CHIMAERA_INCLUDE_CHIMAERA_MONITOR_PREDICT_LOG_H_
