/**
 * Auto-generated execution implementation for bdev ChiMod
 * Implements Container virtual APIs directly using switch-case dispatch
 * 
 * This file is autogenerated - do not edit manually.
 * Changes should be made to the autogen tool or the YAML configuration.
 */

#include "chimaera/bdev/bdev_runtime.h"
#include "chimaera/bdev/autogen/bdev_methods.h"
#include <chimaera/chimaera.h>

namespace chimaera::bdev {

//==============================================================================
// Container Virtual API Implementations
//==============================================================================

void Runtime::Run(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr, chi::RunContext& rctx) {
  switch (method) {
    case Method::kCreate: {
      Create(task_ptr.Cast<CreateTask>(), rctx);
      break;
    }
    case Method::kDestroy: {
      Destroy(task_ptr.Cast<DestroyTask>(), rctx);
      break;
    }
    case Method::kAllocateBlocks: {
      AllocateBlocks(task_ptr.Cast<AllocateBlocksTask>(), rctx);
      break;
    }
    case Method::kFreeBlocks: {
      FreeBlocks(task_ptr.Cast<FreeBlocksTask>(), rctx);
      break;
    }
    case Method::kWrite: {
      Write(task_ptr.Cast<WriteTask>(), rctx);
      break;
    }
    case Method::kRead: {
      Read(task_ptr.Cast<ReadTask>(), rctx);
      break;
    }
    case Method::kGetStats: {
      GetStats(task_ptr.Cast<GetStatsTask>(), rctx);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::Monitor(chi::MonitorModeId mode, chi::u32 method, 
                       hipc::FullPtr<chi::Task> task_ptr, chi::RunContext& rctx) {
  switch (method) {
    case Method::kCreate: {
      MonitorCreate(mode, task_ptr.Cast<CreateTask>(), rctx);
      break;
    }
    case Method::kDestroy: {
      MonitorDestroy(mode, task_ptr.Cast<DestroyTask>(), rctx);
      break;
    }
    case Method::kAllocateBlocks: {
      MonitorAllocateBlocks(mode, task_ptr.Cast<AllocateBlocksTask>(), rctx);
      break;
    }
    case Method::kFreeBlocks: {
      MonitorFreeBlocks(mode, task_ptr.Cast<FreeBlocksTask>(), rctx);
      break;
    }
    case Method::kWrite: {
      MonitorWrite(mode, task_ptr.Cast<WriteTask>(), rctx);
      break;
    }
    case Method::kRead: {
      MonitorRead(mode, task_ptr.Cast<ReadTask>(), rctx);
      break;
    }
    case Method::kGetStats: {
      MonitorGetStats(mode, task_ptr.Cast<GetStatsTask>(), rctx);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::Del(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr) {
  // Use IPC manager to deallocate task from shared memory
  auto* ipc_manager = CHI_IPC;
  
  switch (method) {
    case Method::kCreate: {
      ipc_manager->DelTask(task_ptr.Cast<CreateTask>());
      break;
    }
    case Method::kDestroy: {
      ipc_manager->DelTask(task_ptr.Cast<DestroyTask>());
      break;
    }
    case Method::kAllocateBlocks: {
      ipc_manager->DelTask(task_ptr.Cast<AllocateBlocksTask>());
      break;
    }
    case Method::kFreeBlocks: {
      ipc_manager->DelTask(task_ptr.Cast<FreeBlocksTask>());
      break;
    }
    case Method::kWrite: {
      ipc_manager->DelTask(task_ptr.Cast<WriteTask>());
      break;
    }
    case Method::kRead: {
      ipc_manager->DelTask(task_ptr.Cast<ReadTask>());
      break;
    }
    case Method::kGetStats: {
      ipc_manager->DelTask(task_ptr.Cast<GetStatsTask>());
      break;
    }
    default: {
      // For unknown methods, still try to delete from main segment
      ipc_manager->DelTask(task_ptr);
      break;
    }
  }
}

void Runtime::SaveTask(chi::u32 method, chi::SaveTaskArchive& archive, 
                        hipc::FullPtr<chi::Task> task_ptr) {
  bool srl_mode = archive.GetSerializeMode();
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.Cast<CreateTask>();
      if (srl_mode) {
        typed_task->SerializeIn(archive);
      } else {
        typed_task->SerializeOut(archive);
      }
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.Cast<DestroyTask>();
      if (srl_mode) {
        typed_task->SerializeIn(archive);
      } else {
        typed_task->SerializeOut(archive);
      }
      break;
    }
    case Method::kAllocateBlocks: {
      auto typed_task = task_ptr.Cast<AllocateBlocksTask>();
      if (srl_mode) {
        typed_task->SerializeIn(archive);
      } else {
        typed_task->SerializeOut(archive);
      }
      break;
    }
    case Method::kFreeBlocks: {
      auto typed_task = task_ptr.Cast<FreeBlocksTask>();
      if (srl_mode) {
        typed_task->SerializeIn(archive);
      } else {
        typed_task->SerializeOut(archive);
      }
      break;
    }
    case Method::kWrite: {
      auto typed_task = task_ptr.Cast<WriteTask>();
      if (srl_mode) {
        typed_task->SerializeIn(archive);
      } else {
        typed_task->SerializeOut(archive);
      }
      break;
    }
    case Method::kRead: {
      auto typed_task = task_ptr.Cast<ReadTask>();
      if (srl_mode) {
        typed_task->SerializeIn(archive);
      } else {
        typed_task->SerializeOut(archive);
      }
      break;
    }
    case Method::kGetStats: {
      auto typed_task = task_ptr.Cast<GetStatsTask>();
      if (srl_mode) {
        typed_task->SerializeIn(archive);
      } else {
        typed_task->SerializeOut(archive);
      }
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::LoadTask(chi::u32 method, chi::LoadTaskArchive& archive, 
                        hipc::FullPtr<chi::Task> task_ptr) {
  bool srl_mode = archive.GetSerializeMode();
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.Cast<CreateTask>();
      if (srl_mode) {
        typed_task->SerializeIn(archive);
      } else {
        typed_task->SerializeOut(archive);
      }
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.Cast<DestroyTask>();
      if (srl_mode) {
        typed_task->SerializeIn(archive);
      } else {
        typed_task->SerializeOut(archive);
      }
      break;
    }
    case Method::kAllocateBlocks: {
      auto typed_task = task_ptr.Cast<AllocateBlocksTask>();
      if (srl_mode) {
        typed_task->SerializeIn(archive);
      } else {
        typed_task->SerializeOut(archive);
      }
      break;
    }
    case Method::kFreeBlocks: {
      auto typed_task = task_ptr.Cast<FreeBlocksTask>();
      if (srl_mode) {
        typed_task->SerializeIn(archive);
      } else {
        typed_task->SerializeOut(archive);
      }
      break;
    }
    case Method::kWrite: {
      auto typed_task = task_ptr.Cast<WriteTask>();
      if (srl_mode) {
        typed_task->SerializeIn(archive);
      } else {
        typed_task->SerializeOut(archive);
      }
      break;
    }
    case Method::kRead: {
      auto typed_task = task_ptr.Cast<ReadTask>();
      if (srl_mode) {
        typed_task->SerializeIn(archive);
      } else {
        typed_task->SerializeOut(archive);
      }
      break;
    }
    case Method::kGetStats: {
      auto typed_task = task_ptr.Cast<GetStatsTask>();
      if (srl_mode) {
        typed_task->SerializeIn(archive);
      } else {
        typed_task->SerializeOut(archive);
      }
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::NewCopy(chi::u32 method, const hipc::FullPtr<chi::Task>& orig_task,
                       hipc::FullPtr<chi::Task>& dup_task, bool deep) {
  auto* ipc_manager = CHI_IPC;
  if (!ipc_manager) {
    return;
  }
  
  switch (method) {
    case Method::kCreate: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<CreateTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<CreateTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kDestroy: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<DestroyTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<DestroyTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kAllocateBlocks: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<AllocateBlocksTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<AllocateBlocksTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kFreeBlocks: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<FreeBlocksTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<FreeBlocksTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kWrite: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<WriteTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<WriteTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kRead: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<ReadTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<ReadTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kGetStats: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<GetStatsTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<GetStatsTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    default: {
      // For unknown methods, create base Task copy
      auto typed_task = ipc_manager->NewTask<chi::Task>();
      if (!typed_task.IsNull()) {
        typed_task->shm_strong_copy_main(*orig_task);
        dup_task = typed_task;  // Already chi::Task type
      }
      break;
    }
  }
  
  (void)deep;    // Deep copy parameter reserved for future use
}

} // namespace chimaera::bdev
