/**
 * Auto-generated execution implementation for bdev ChiMod
 * Implements Container virtual APIs directly using switch-case dispatch
 * 
 * This file is autogenerated - do not edit manually.
 * Changes should be made to the autogen tool or the YAML configuration.
 */

#include "chimaera/bdev/bdev_runtime.h"
#include "chimaera/bdev/autogen/bdev_methods.h"
#include <chimaera/chimaera.h>

namespace chimaera::bdev {

//==============================================================================
// Container Virtual API Implementations
//==============================================================================

void Runtime::Run(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr, chi::RunContext& rctx) {
  switch (method) {
    case Method::kCreate: {
      Create(task_ptr.Cast<CreateTask>(), rctx);
      break;
    }
    case Method::kDestroy: {
      Destroy(task_ptr.Cast<DestroyTask>(), rctx);
      break;
    }
    case Method::kAllocateBlocks: {
      AllocateBlocks(task_ptr.Cast<AllocateBlocksTask>(), rctx);
      break;
    }
    case Method::kFreeBlocks: {
      FreeBlocks(task_ptr.Cast<FreeBlocksTask>(), rctx);
      break;
    }
    case Method::kWrite: {
      Write(task_ptr.Cast<WriteTask>(), rctx);
      break;
    }
    case Method::kRead: {
      Read(task_ptr.Cast<ReadTask>(), rctx);
      break;
    }
    case Method::kGetStats: {
      GetStats(task_ptr.Cast<GetStatsTask>(), rctx);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::Del(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr) {
  // Use IPC manager to deallocate task from shared memory
  auto* ipc_manager = CHI_IPC;
  
  switch (method) {
    case Method::kCreate: {
      ipc_manager->DelTask(task_ptr.Cast<CreateTask>());
      break;
    }
    case Method::kDestroy: {
      ipc_manager->DelTask(task_ptr.Cast<DestroyTask>());
      break;
    }
    case Method::kAllocateBlocks: {
      ipc_manager->DelTask(task_ptr.Cast<AllocateBlocksTask>());
      break;
    }
    case Method::kFreeBlocks: {
      ipc_manager->DelTask(task_ptr.Cast<FreeBlocksTask>());
      break;
    }
    case Method::kWrite: {
      ipc_manager->DelTask(task_ptr.Cast<WriteTask>());
      break;
    }
    case Method::kRead: {
      ipc_manager->DelTask(task_ptr.Cast<ReadTask>());
      break;
    }
    case Method::kGetStats: {
      ipc_manager->DelTask(task_ptr.Cast<GetStatsTask>());
      break;
    }
    default: {
      // For unknown methods, still try to delete from main segment
      ipc_manager->DelTask(task_ptr);
      break;
    }
  }
}

void Runtime::SaveTask(chi::u32 method, chi::SaveTaskArchive& archive, 
                        hipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.Cast<CreateTask>();
      archive << *typed_task;
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.Cast<DestroyTask>();
      archive << *typed_task;
      break;
    }
    case Method::kAllocateBlocks: {
      auto typed_task = task_ptr.Cast<AllocateBlocksTask>();
      archive << *typed_task;
      break;
    }
    case Method::kFreeBlocks: {
      auto typed_task = task_ptr.Cast<FreeBlocksTask>();
      archive << *typed_task;
      break;
    }
    case Method::kWrite: {
      auto typed_task = task_ptr.Cast<WriteTask>();
      archive << *typed_task;
      break;
    }
    case Method::kRead: {
      auto typed_task = task_ptr.Cast<ReadTask>();
      archive << *typed_task;
      break;
    }
    case Method::kGetStats: {
      auto typed_task = task_ptr.Cast<GetStatsTask>();
      archive << *typed_task;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::LoadTask(chi::u32 method, chi::LoadTaskArchive& archive, 
                        hipc::FullPtr<chi::Task>& task_ptr) {
  auto* ipc_manager = CHI_IPC;
  
  switch (method) {
    case Method::kCreate: {
      // Allocate task using typed NewTask if not already allocated
      if (task_ptr.IsNull()) {
        task_ptr = ipc_manager->NewTask<CreateTask>().template Cast<chi::Task>();
      }
      auto typed_task = task_ptr.Cast<CreateTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kDestroy: {
      // Allocate task using typed NewTask if not already allocated
      if (task_ptr.IsNull()) {
        task_ptr = ipc_manager->NewTask<DestroyTask>().template Cast<chi::Task>();
      }
      auto typed_task = task_ptr.Cast<DestroyTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kAllocateBlocks: {
      // Allocate task using typed NewTask if not already allocated
      if (task_ptr.IsNull()) {
        task_ptr = ipc_manager->NewTask<AllocateBlocksTask>().template Cast<chi::Task>();
      }
      auto typed_task = task_ptr.Cast<AllocateBlocksTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kFreeBlocks: {
      // Allocate task using typed NewTask if not already allocated
      if (task_ptr.IsNull()) {
        task_ptr = ipc_manager->NewTask<FreeBlocksTask>().template Cast<chi::Task>();
      }
      auto typed_task = task_ptr.Cast<FreeBlocksTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kWrite: {
      // Allocate task using typed NewTask if not already allocated
      if (task_ptr.IsNull()) {
        task_ptr = ipc_manager->NewTask<WriteTask>().template Cast<chi::Task>();
      }
      auto typed_task = task_ptr.Cast<WriteTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kRead: {
      // Allocate task using typed NewTask if not already allocated
      if (task_ptr.IsNull()) {
        task_ptr = ipc_manager->NewTask<ReadTask>().template Cast<chi::Task>();
      }
      auto typed_task = task_ptr.Cast<ReadTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kGetStats: {
      // Allocate task using typed NewTask if not already allocated
      if (task_ptr.IsNull()) {
        task_ptr = ipc_manager->NewTask<GetStatsTask>().template Cast<chi::Task>();
      }
      auto typed_task = task_ptr.Cast<GetStatsTask>();
      archive >> *typed_task;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::NewCopy(chi::u32 method, const hipc::FullPtr<chi::Task>& orig_task,
                       hipc::FullPtr<chi::Task>& dup_task, bool deep) {
  auto* ipc_manager = CHI_IPC;
  if (!ipc_manager) {
    return;
  }
  
  switch (method) {
    case Method::kCreate: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<CreateTask>();
      if (!typed_task.IsNull()) {
        // Copy base Task fields first
        typed_task.template Cast<chi::Task>()->Copy(orig_task);
        // Then copy task-specific fields
        typed_task->Copy(orig_task.Cast<CreateTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kDestroy: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<DestroyTask>();
      if (!typed_task.IsNull()) {
        // Copy base Task fields first
        typed_task.template Cast<chi::Task>()->Copy(orig_task);
        // Then copy task-specific fields
        typed_task->Copy(orig_task.Cast<DestroyTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kAllocateBlocks: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<AllocateBlocksTask>();
      if (!typed_task.IsNull()) {
        // Copy base Task fields first
        typed_task.template Cast<chi::Task>()->Copy(orig_task);
        // Then copy task-specific fields
        typed_task->Copy(orig_task.Cast<AllocateBlocksTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kFreeBlocks: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<FreeBlocksTask>();
      if (!typed_task.IsNull()) {
        // Copy base Task fields first
        typed_task.template Cast<chi::Task>()->Copy(orig_task);
        // Then copy task-specific fields
        typed_task->Copy(orig_task.Cast<FreeBlocksTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kWrite: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<WriteTask>();
      if (!typed_task.IsNull()) {
        // Copy base Task fields first
        typed_task.template Cast<chi::Task>()->Copy(orig_task);
        // Then copy task-specific fields
        typed_task->Copy(orig_task.Cast<WriteTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kRead: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<ReadTask>();
      if (!typed_task.IsNull()) {
        // Copy base Task fields first
        typed_task.template Cast<chi::Task>()->Copy(orig_task);
        // Then copy task-specific fields
        typed_task->Copy(orig_task.Cast<ReadTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kGetStats: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<GetStatsTask>();
      if (!typed_task.IsNull()) {
        // Copy base Task fields first
        typed_task.template Cast<chi::Task>()->Copy(orig_task);
        // Then copy task-specific fields
        typed_task->Copy(orig_task.Cast<GetStatsTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    default: {
      // For unknown methods, create base Task copy
      auto typed_task = ipc_manager->NewTask<chi::Task>();
      if (!typed_task.IsNull()) {
        typed_task->Copy(orig_task);
        dup_task = typed_task;  // Already chi::Task type
      }
      break;
    }
  }
  
  (void)deep;    // Deep copy parameter reserved for future use
}

void Runtime::Aggregate(chi::u32 method, hipc::FullPtr<chi::Task> origin_task,
                         hipc::FullPtr<chi::Task> replica_task) {
  switch (method) {
    case Method::kCreate: {
      auto typed_origin = origin_task.Cast<CreateTask>();
      auto typed_replica = replica_task.Cast<CreateTask>();
      // Use SFINAE-based macro to call Aggregate if available, otherwise Copy
      CHI_AGGREGATE_OR_COPY(typed_origin, typed_replica);
      break;
    }
    case Method::kDestroy: {
      auto typed_origin = origin_task.Cast<DestroyTask>();
      auto typed_replica = replica_task.Cast<DestroyTask>();
      // Use SFINAE-based macro to call Aggregate if available, otherwise Copy
      CHI_AGGREGATE_OR_COPY(typed_origin, typed_replica);
      break;
    }
    case Method::kAllocateBlocks: {
      auto typed_origin = origin_task.Cast<AllocateBlocksTask>();
      auto typed_replica = replica_task.Cast<AllocateBlocksTask>();
      // Use SFINAE-based macro to call Aggregate if available, otherwise Copy
      CHI_AGGREGATE_OR_COPY(typed_origin, typed_replica);
      break;
    }
    case Method::kFreeBlocks: {
      auto typed_origin = origin_task.Cast<FreeBlocksTask>();
      auto typed_replica = replica_task.Cast<FreeBlocksTask>();
      // Use SFINAE-based macro to call Aggregate if available, otherwise Copy
      CHI_AGGREGATE_OR_COPY(typed_origin, typed_replica);
      break;
    }
    case Method::kWrite: {
      auto typed_origin = origin_task.Cast<WriteTask>();
      auto typed_replica = replica_task.Cast<WriteTask>();
      // Use SFINAE-based macro to call Aggregate if available, otherwise Copy
      CHI_AGGREGATE_OR_COPY(typed_origin, typed_replica);
      break;
    }
    case Method::kRead: {
      auto typed_origin = origin_task.Cast<ReadTask>();
      auto typed_replica = replica_task.Cast<ReadTask>();
      // Use SFINAE-based macro to call Aggregate if available, otherwise Copy
      CHI_AGGREGATE_OR_COPY(typed_origin, typed_replica);
      break;
    }
    case Method::kGetStats: {
      auto typed_origin = origin_task.Cast<GetStatsTask>();
      auto typed_replica = replica_task.Cast<GetStatsTask>();
      // Use SFINAE-based macro to call Aggregate if available, otherwise Copy
      CHI_AGGREGATE_OR_COPY(typed_origin, typed_replica);
      break;
    }
    default: {
      // For unknown methods, use base Task Copy
      origin_task->Copy(replica_task);
      break;
    }
  }
}

} // namespace chimaera::bdev
