/**
 * Auto-generated execution implementation for simple_mod ChiMod
 * Implements Container virtual APIs directly using switch-case dispatch
 * 
 * This file is autogenerated - do not edit manually.
 * Changes should be made to the autogen tool or the YAML configuration.
 */

#include "chimaera/simple_mod/simple_mod_runtime.h"
#include "chimaera/simple_mod/autogen/simple_mod_methods.h"
#include <chimaera/chimaera.h>

namespace external_test::simple_mod {

//==============================================================================
// Container Virtual API Implementations
//==============================================================================

void Runtime::Run(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr, chi::RunContext& rctx) {
  switch (method) {
    case Method::kCreate: {
      Create(task_ptr.Cast<CreateTask>(), rctx);
      break;
    }
    case Method::kDestroy: {
      Destroy(task_ptr.Cast<DestroyTask>(), rctx);
      break;
    }
    case Method::kFlush: {
      Flush(task_ptr.Cast<FlushTask>(), rctx);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::Monitor(chi::MonitorModeId mode, chi::u32 method, 
                       hipc::FullPtr<chi::Task> task_ptr, chi::RunContext& rctx) {
  switch (method) {
    case Method::kCreate: {
      MonitorCreate(mode, task_ptr.Cast<CreateTask>(), rctx);
      break;
    }
    case Method::kDestroy: {
      MonitorDestroy(mode, task_ptr.Cast<DestroyTask>(), rctx);
      break;
    }
    case Method::kFlush: {
      MonitorFlush(mode, task_ptr.Cast<FlushTask>(), rctx);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::Del(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate:
    case Method::kDestroy:
    case Method::kFlush:
    default: {
      // For simple_mod, no special cleanup needed for any task type
      // Base task destruction is handled by the framework
      break;
    }
  }
}

//==============================================================================
// Module Registration
//==============================================================================

} // namespace external_test::simple_mod

//==============================================================================
// Global Registration Function
//==============================================================================

// Factory function for creating instances of this ChiMod Runtime
CHI_TASK_CC(external_test::simple_mod::Runtime)