/**
 * Auto-generated execution implementation for admin ChiMod
 * Implements Container virtual APIs directly using switch-case dispatch
 * 
 * This file is autogenerated - do not edit manually.
 * Changes should be made to the autogen tool or the YAML configuration.
 */

#include "chimaera/admin/admin_runtime.h"
#include "chimaera/admin/autogen/admin_methods.h"
#include <chimaera/chimaera.h>

namespace chimaera::admin {

//==============================================================================
// Container Virtual API Implementations
//==============================================================================

void Runtime::Run(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr, chi::RunContext& rctx) {
  switch (method) {
    case Method::kCreate: {
      Create(task_ptr.Cast<CreateTask>(), rctx);
      break;
    }
    case Method::kDestroy: {
      Destroy(task_ptr.Cast<DestroyTask>(), rctx);
      break;
    }
    case Method::kGetOrCreatePool: {
      GetOrCreatePool(task_ptr.Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>(), rctx);
      break;
    }
    case Method::kDestroyPool: {
      DestroyPool(task_ptr.Cast<DestroyPoolTask>(), rctx);
      break;
    }
    case Method::kStopRuntime: {
      StopRuntime(task_ptr.Cast<StopRuntimeTask>(), rctx);
      break;
    }
    case Method::kFlush: {
      Flush(task_ptr.Cast<FlushTask>(), rctx);
      break;
    }
    case Method::kSend: {
      Send(task_ptr.Cast<SendTask>(), rctx);
      break;
    }
    case Method::kRecv: {
      Recv(task_ptr.Cast<RecvTask>(), rctx);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::Monitor(chi::MonitorModeId mode, chi::u32 method, 
                       hipc::FullPtr<chi::Task> task_ptr, chi::RunContext& rctx) {
  switch (method) {
    case Method::kCreate: {
      MonitorCreate(mode, task_ptr.Cast<CreateTask>(), rctx);
      break;
    }
    case Method::kDestroy: {
      MonitorDestroy(mode, task_ptr.Cast<DestroyTask>(), rctx);
      break;
    }
    case Method::kGetOrCreatePool: {
      MonitorGetOrCreatePool(mode, task_ptr.Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>(), rctx);
      break;
    }
    case Method::kDestroyPool: {
      MonitorDestroyPool(mode, task_ptr.Cast<DestroyPoolTask>(), rctx);
      break;
    }
    case Method::kStopRuntime: {
      MonitorStopRuntime(mode, task_ptr.Cast<StopRuntimeTask>(), rctx);
      break;
    }
    case Method::kFlush: {
      MonitorFlush(mode, task_ptr.Cast<FlushTask>(), rctx);
      break;
    }
    case Method::kSend: {
      MonitorSend(mode, task_ptr.Cast<SendTask>(), rctx);
      break;
    }
    case Method::kRecv: {
      MonitorRecv(mode, task_ptr.Cast<RecvTask>(), rctx);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::Del(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr) {
  // Use IPC manager to deallocate task from shared memory
  auto* ipc_manager = CHI_IPC;
  
  switch (method) {
    case Method::kCreate: {
      ipc_manager->DelTask(task_ptr.Cast<CreateTask>());
      break;
    }
    case Method::kDestroy: {
      ipc_manager->DelTask(task_ptr.Cast<DestroyTask>());
      break;
    }
    case Method::kGetOrCreatePool: {
      ipc_manager->DelTask(task_ptr.Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>());
      break;
    }
    case Method::kDestroyPool: {
      ipc_manager->DelTask(task_ptr.Cast<DestroyPoolTask>());
      break;
    }
    case Method::kStopRuntime: {
      ipc_manager->DelTask(task_ptr.Cast<StopRuntimeTask>());
      break;
    }
    case Method::kFlush: {
      ipc_manager->DelTask(task_ptr.Cast<FlushTask>());
      break;
    }
    case Method::kSend: {
      ipc_manager->DelTask(task_ptr.Cast<SendTask>());
      break;
    }
    case Method::kRecv: {
      ipc_manager->DelTask(task_ptr.Cast<RecvTask>());
      break;
    }
    default: {
      // For unknown methods, still try to delete from main segment
      ipc_manager->DelTask(task_ptr);
      break;
    }
  }
}

void Runtime::SaveTask(chi::u32 method, chi::SaveTaskArchive& archive, 
                        hipc::FullPtr<chi::Task> task_ptr) {
  bool srl_mode = archive.GetSerializeMode();
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.Cast<CreateTask>();
      if (srl_mode) {
        typed_task->SerializeIn(archive);
      } else {
        typed_task->SerializeOut(archive);
      }
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.Cast<DestroyTask>();
      if (srl_mode) {
        typed_task->SerializeIn(archive);
      } else {
        typed_task->SerializeOut(archive);
      }
      break;
    }
    case Method::kGetOrCreatePool: {
      auto typed_task = task_ptr.Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>();
      if (srl_mode) {
        typed_task->SerializeIn(archive);
      } else {
        typed_task->SerializeOut(archive);
      }
      break;
    }
    case Method::kDestroyPool: {
      auto typed_task = task_ptr.Cast<DestroyPoolTask>();
      if (srl_mode) {
        typed_task->SerializeIn(archive);
      } else {
        typed_task->SerializeOut(archive);
      }
      break;
    }
    case Method::kStopRuntime: {
      auto typed_task = task_ptr.Cast<StopRuntimeTask>();
      if (srl_mode) {
        typed_task->SerializeIn(archive);
      } else {
        typed_task->SerializeOut(archive);
      }
      break;
    }
    case Method::kFlush: {
      auto typed_task = task_ptr.Cast<FlushTask>();
      if (srl_mode) {
        typed_task->SerializeIn(archive);
      } else {
        typed_task->SerializeOut(archive);
      }
      break;
    }
    case Method::kSend: {
      auto typed_task = task_ptr.Cast<SendTask>();
      if (srl_mode) {
        typed_task->SerializeIn(archive);
      } else {
        typed_task->SerializeOut(archive);
      }
      break;
    }
    case Method::kRecv: {
      auto typed_task = task_ptr.Cast<RecvTask>();
      if (srl_mode) {
        typed_task->SerializeIn(archive);
      } else {
        typed_task->SerializeOut(archive);
      }
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::LoadTask(chi::u32 method, chi::LoadTaskArchive& archive, 
                        hipc::FullPtr<chi::Task> task_ptr) {
  bool srl_mode = archive.GetSerializeMode();
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.Cast<CreateTask>();
      if (srl_mode) {
        typed_task->SerializeIn(archive);
      } else {
        typed_task->SerializeOut(archive);
      }
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.Cast<DestroyTask>();
      if (srl_mode) {
        typed_task->SerializeIn(archive);
      } else {
        typed_task->SerializeOut(archive);
      }
      break;
    }
    case Method::kGetOrCreatePool: {
      auto typed_task = task_ptr.Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>();
      if (srl_mode) {
        typed_task->SerializeIn(archive);
      } else {
        typed_task->SerializeOut(archive);
      }
      break;
    }
    case Method::kDestroyPool: {
      auto typed_task = task_ptr.Cast<DestroyPoolTask>();
      if (srl_mode) {
        typed_task->SerializeIn(archive);
      } else {
        typed_task->SerializeOut(archive);
      }
      break;
    }
    case Method::kStopRuntime: {
      auto typed_task = task_ptr.Cast<StopRuntimeTask>();
      if (srl_mode) {
        typed_task->SerializeIn(archive);
      } else {
        typed_task->SerializeOut(archive);
      }
      break;
    }
    case Method::kFlush: {
      auto typed_task = task_ptr.Cast<FlushTask>();
      if (srl_mode) {
        typed_task->SerializeIn(archive);
      } else {
        typed_task->SerializeOut(archive);
      }
      break;
    }
    case Method::kSend: {
      auto typed_task = task_ptr.Cast<SendTask>();
      if (srl_mode) {
        typed_task->SerializeIn(archive);
      } else {
        typed_task->SerializeOut(archive);
      }
      break;
    }
    case Method::kRecv: {
      auto typed_task = task_ptr.Cast<RecvTask>();
      if (srl_mode) {
        typed_task->SerializeIn(archive);
      } else {
        typed_task->SerializeOut(archive);
      }
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::NewCopy(chi::u32 method, const hipc::FullPtr<chi::Task>& orig_task,
                       hipc::FullPtr<chi::Task>& dup_task, bool deep) {
  auto* ipc_manager = CHI_IPC;
  if (!ipc_manager) {
    return;
  }
  
  switch (method) {
    case Method::kCreate: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<CreateTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<CreateTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kDestroy: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<DestroyTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<DestroyTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kGetOrCreatePool: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<admin::GetOrCreatePoolTask<admin::CreateParams>>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kDestroyPool: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<DestroyPoolTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<DestroyPoolTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kStopRuntime: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<StopRuntimeTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<StopRuntimeTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kFlush: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<FlushTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<FlushTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kSend: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<SendTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<SendTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kRecv: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<RecvTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<RecvTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    default: {
      // For unknown methods, create base Task copy
      auto typed_task = ipc_manager->NewTask<chi::Task>();
      if (!typed_task.IsNull()) {
        typed_task->shm_strong_copy_main(*orig_task);
        dup_task = typed_task;  // Already chi::Task type
      }
      break;
    }
  }
  
  (void)deep;    // Deep copy parameter reserved for future use
}

} // namespace chimaera::admin
