/**
 * Auto-generated execution implementation for admin ChiMod
 * Implements Container virtual APIs directly using switch-case dispatch
 * 
 * This file is autogenerated - do not edit manually.
 * Changes should be made to the autogen tool or the YAML configuration.
 */

#include "admin/admin_runtime.h"
#include "admin/autogen/admin_methods.h"
#include <chimaera/chimaera.h>

namespace chimaera::admin {

//==============================================================================
// Container Virtual API Implementations
//==============================================================================

void Runtime::Run(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr, chi::RunContext& rctx) {
  switch (method) {
    case Method::kCreate: {
      Create(task_ptr.Cast<CreateTask>(), rctx);
      break;
    }
    case Method::kDestroy: {
      Destroy(task_ptr.Cast<DestroyTask>(), rctx);
      break;
    }
    case Method::kGetOrCreatePool: {
      GetOrCreatePool(task_ptr.Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>(), rctx);
      break;
    }
    case Method::kDestroyPool: {
      DestroyPool(task_ptr.Cast<DestroyPoolTask>(), rctx);
      break;
    }
    case Method::kStopRuntime: {
      StopRuntime(task_ptr.Cast<StopRuntimeTask>(), rctx);
      break;
    }
    case Method::kFlush: {
      Flush(task_ptr.Cast<FlushTask>(), rctx);
      break;
    }
    case Method::kClientSendTaskIn: {
      ClientSendTaskIn(task_ptr.Cast<ClientSendTaskInTask>(), rctx);
      break;
    }
    case Method::kServerRecvTaskIn: {
      ServerRecvTaskIn(task_ptr.Cast<ServerRecvTaskInTask>(), rctx);
      break;
    }
    case Method::kServerSendTaskOut: {
      ServerSendTaskOut(task_ptr.Cast<ServerSendTaskOutTask>(), rctx);
      break;
    }
    case Method::kClientRecvTaskOut: {
      ClientRecvTaskOut(task_ptr.Cast<ClientRecvTaskOutTask>(), rctx);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::Monitor(chi::MonitorModeId mode, chi::u32 method, 
                       hipc::FullPtr<chi::Task> task_ptr, chi::RunContext& rctx) {
  switch (method) {
    case Method::kCreate: {
      MonitorCreate(mode, task_ptr.Cast<CreateTask>(), rctx);
      break;
    }
    case Method::kDestroy: {
      MonitorDestroy(mode, task_ptr.Cast<DestroyTask>(), rctx);
      break;
    }
    case Method::kGetOrCreatePool: {
      MonitorGetOrCreatePool(mode, task_ptr.Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>(), rctx);
      break;
    }
    case Method::kDestroyPool: {
      MonitorDestroyPool(mode, task_ptr.Cast<DestroyPoolTask>(), rctx);
      break;
    }
    case Method::kStopRuntime: {
      MonitorStopRuntime(mode, task_ptr.Cast<StopRuntimeTask>(), rctx);
      break;
    }
    case Method::kFlush: {
      MonitorFlush(mode, task_ptr.Cast<FlushTask>(), rctx);
      break;
    }
    case Method::kClientSendTaskIn: {
      MonitorClientSendTaskIn(mode, task_ptr.Cast<ClientSendTaskInTask>(), rctx);
      break;
    }
    case Method::kServerRecvTaskIn: {
      MonitorServerRecvTaskIn(mode, task_ptr.Cast<ServerRecvTaskInTask>(), rctx);
      break;
    }
    case Method::kServerSendTaskOut: {
      MonitorServerSendTaskOut(mode, task_ptr.Cast<ServerSendTaskOutTask>(), rctx);
      break;
    }
    case Method::kClientRecvTaskOut: {
      MonitorClientRecvTaskOut(mode, task_ptr.Cast<ClientRecvTaskOutTask>(), rctx);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::Del(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr) {
  // Use IPC manager to deallocate task from shared memory
  auto* ipc_manager = CHI_IPC;
  
  switch (method) {
    case Method::kCreate: {
      ipc_manager->DelTask(task_ptr.Cast<CreateTask>());
      break;
    }
    case Method::kDestroy: {
      ipc_manager->DelTask(task_ptr.Cast<DestroyTask>());
      break;
    }
    case Method::kGetOrCreatePool: {
      ipc_manager->DelTask(task_ptr.Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>());
      break;
    }
    case Method::kDestroyPool: {
      ipc_manager->DelTask(task_ptr.Cast<DestroyPoolTask>());
      break;
    }
    case Method::kStopRuntime: {
      ipc_manager->DelTask(task_ptr.Cast<StopRuntimeTask>());
      break;
    }
    case Method::kFlush: {
      ipc_manager->DelTask(task_ptr.Cast<FlushTask>());
      break;
    }
    case Method::kClientSendTaskIn: {
      ipc_manager->DelTask(task_ptr.Cast<ClientSendTaskInTask>());
      break;
    }
    case Method::kServerRecvTaskIn: {
      ipc_manager->DelTask(task_ptr.Cast<ServerRecvTaskInTask>());
      break;
    }
    case Method::kServerSendTaskOut: {
      ipc_manager->DelTask(task_ptr.Cast<ServerSendTaskOutTask>());
      break;
    }
    case Method::kClientRecvTaskOut: {
      ipc_manager->DelTask(task_ptr.Cast<ClientRecvTaskOutTask>());
      break;
    }
    default: {
      // For unknown methods, still try to delete from main segment
      ipc_manager->DelTask(task_ptr);
      break;
    }
  }
}

void Runtime::SaveIn(chi::u32 method, chi::TaskSaveInArchive& archive, 
                      hipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.Cast<CreateTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.Cast<DestroyTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kGetOrCreatePool: {
      auto typed_task = task_ptr.Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kDestroyPool: {
      auto typed_task = task_ptr.Cast<DestroyPoolTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kStopRuntime: {
      auto typed_task = task_ptr.Cast<StopRuntimeTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kFlush: {
      auto typed_task = task_ptr.Cast<FlushTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kClientSendTaskIn: {
      auto typed_task = task_ptr.Cast<ClientSendTaskInTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kServerRecvTaskIn: {
      auto typed_task = task_ptr.Cast<ServerRecvTaskInTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kServerSendTaskOut: {
      auto typed_task = task_ptr.Cast<ServerSendTaskOutTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kClientRecvTaskOut: {
      auto typed_task = task_ptr.Cast<ClientRecvTaskOutTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::LoadIn(chi::u32 method, chi::TaskLoadInArchive& archive, 
                      hipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.Cast<CreateTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.Cast<DestroyTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kGetOrCreatePool: {
      auto typed_task = task_ptr.Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kDestroyPool: {
      auto typed_task = task_ptr.Cast<DestroyPoolTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kStopRuntime: {
      auto typed_task = task_ptr.Cast<StopRuntimeTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kFlush: {
      auto typed_task = task_ptr.Cast<FlushTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kClientSendTaskIn: {
      auto typed_task = task_ptr.Cast<ClientSendTaskInTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kServerRecvTaskIn: {
      auto typed_task = task_ptr.Cast<ServerRecvTaskInTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kServerSendTaskOut: {
      auto typed_task = task_ptr.Cast<ServerSendTaskOutTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kClientRecvTaskOut: {
      auto typed_task = task_ptr.Cast<ClientRecvTaskOutTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::SaveOut(chi::u32 method, chi::TaskSaveOutArchive& archive, 
                       hipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.Cast<CreateTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.Cast<DestroyTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kGetOrCreatePool: {
      auto typed_task = task_ptr.Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kDestroyPool: {
      auto typed_task = task_ptr.Cast<DestroyPoolTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kStopRuntime: {
      auto typed_task = task_ptr.Cast<StopRuntimeTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kFlush: {
      auto typed_task = task_ptr.Cast<FlushTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kClientSendTaskIn: {
      auto typed_task = task_ptr.Cast<ClientSendTaskInTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kServerRecvTaskIn: {
      auto typed_task = task_ptr.Cast<ServerRecvTaskInTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kServerSendTaskOut: {
      auto typed_task = task_ptr.Cast<ServerSendTaskOutTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kClientRecvTaskOut: {
      auto typed_task = task_ptr.Cast<ClientRecvTaskOutTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::LoadOut(chi::u32 method, chi::TaskLoadOutArchive& archive, 
                       hipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.Cast<CreateTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.Cast<DestroyTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kGetOrCreatePool: {
      auto typed_task = task_ptr.Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kDestroyPool: {
      auto typed_task = task_ptr.Cast<DestroyPoolTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kStopRuntime: {
      auto typed_task = task_ptr.Cast<StopRuntimeTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kFlush: {
      auto typed_task = task_ptr.Cast<FlushTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kClientSendTaskIn: {
      auto typed_task = task_ptr.Cast<ClientSendTaskInTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kServerRecvTaskIn: {
      auto typed_task = task_ptr.Cast<ServerRecvTaskInTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kServerSendTaskOut: {
      auto typed_task = task_ptr.Cast<ServerSendTaskOutTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kClientRecvTaskOut: {
      auto typed_task = task_ptr.Cast<ClientRecvTaskOutTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::NewCopy(chi::u32 method, const hipc::FullPtr<chi::Task>& orig_task,
                       hipc::FullPtr<chi::Task>& dup_task, bool deep) {
  auto* ipc_manager = CHI_IPC;
  if (!ipc_manager) {
    return;
  }
  
  switch (method) {
    case Method::kCreate: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<CreateTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<CreateTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kDestroy: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<DestroyTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<DestroyTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kGetOrCreatePool: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<admin::GetOrCreatePoolTask<admin::CreateParams>>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kDestroyPool: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<DestroyPoolTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<DestroyPoolTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kStopRuntime: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<StopRuntimeTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<StopRuntimeTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kFlush: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<FlushTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<FlushTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kClientSendTaskIn: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<ClientSendTaskInTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<ClientSendTaskInTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kServerRecvTaskIn: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<ServerRecvTaskInTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<ServerRecvTaskInTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kServerSendTaskOut: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<ServerSendTaskOutTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<ServerSendTaskOutTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kClientRecvTaskOut: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<ClientRecvTaskOutTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<ClientRecvTaskOutTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    default: {
      // For unknown methods, create base Task copy
      auto typed_task = ipc_manager->NewTask<chi::Task>();
      if (!typed_task.IsNull()) {
        typed_task->shm_strong_copy_main(*orig_task);
        dup_task = typed_task;  // Already chi::Task type
      }
      break;
    }
  }
  
  (void)deep;    // Deep copy parameter reserved for future use
}

} // namespace chimaera::admin
