#!/usr/bin/env python3

"""
USAGE:
    cd codegen/bin
    python3 make_config.py

OUTPUT:
    ${CHI}/src/config_client_default.h (if client)
    ${CHI}/src/config_server_default.h (if server)
"""

from codegen.chimaera_config.generator import create_config
from codegen.util.paths import CHIMEARA_ROOT

create_config(
    path=f"{CHIMEARA_ROOT}/config/chimaera_client_default.yaml",
    var_name="kChiDefaultClientConfigStr",
    config_path=f"{CHIMEARA_ROOT}/include/chimaera/config/config_client_default.h",
    macro_name="CHI_CLIENT"
)

create_config(
    path=f"{CHIMEARA_ROOT}/config/chimaera_server_default.yaml",
    var_name="kChiServerDefaultConfigStr",
    config_path=f"{CHIMEARA_ROOT}/include/chimaera/config/config_server_default.h",
    macro_name="CHI_SERVER"
)