#!/usr/bin/env python3

"""
USAGE:
    cd codegen/bin
    python3 make_config.py

OUTPUT:
    ${HRUN}/src/config_client_default.h (if client)
    ${HRUN}/src/config_server_default.h (if server)
"""

from codegen.chimaera_config.generator import create_config
from codegen.util.paths import CHIMEARA_ROOT

create_config(
    path=f"{CHIMEARA_ROOT}/config/chimaera_client_default.yaml",
    var_name="kHrunClientDefaultConfigStr",
    config_path=f"{CHIMEARA_ROOT}/include/chimaera/config/config_client_default.h",
    macro_name="CHM_CLIENT"
)

create_config(
    path=f"{CHIMEARA_ROOT}/config/chimaera_server_default.yaml",
    var_name="kHrunServerDefaultConfigStr",
    config_path=f"{CHIMEARA_ROOT}/include/chimaera/config/config_server_default.h",
    macro_name="HRUN_SERVER"
)