#!/usr/bin/env python3

"""
USAGE: ./referesh_methods [TASK_DIR]
"""

import yaml
import os
import sys

def refresh_methods(TASK_ROOT):
    if not os.path.exists(f'{TASK_ROOT}/include'):
        return
    TASK_NAME = os.path.basename(TASK_ROOT)
    METHODS_H = f'{TASK_ROOT}/include/{TASK_NAME}/{TASK_NAME}_methods.h'
    METHODS_YAML = f'{TASK_ROOT}/include/{TASK_NAME}/{TASK_NAME}_methods.yaml'
    LIB_EXEC_H = f'{TASK_ROOT}/include/{TASK_NAME}/{TASK_NAME}_lib_exec.h'
    METHOD_MACRO = f'CHI_{TASK_NAME.upper()}_METHODS_H_'
    LIB_EXEC_MACRO = f'CHI_{TASK_NAME.upper()}_LIB_EXEC_H_'

    with open(METHODS_YAML) as fp:
        methods = yaml.load(fp, Loader=yaml.FullLoader)
    if methods is None:
        methods = {}
    methods = sorted(methods.items(), key=lambda x: x[1])
    monitor_modes = ['kEstLoad', 'kTrainTime', 'kFlushStat']

    # Produce the TASK_NAME_methods.h file
    lines = []
    lines += [f'#ifndef {METHOD_MACRO}',
              f'#define {METHOD_MACRO}',
              '',
              '/** The set of methods in the admin task */',
              'struct Method : public TaskMethod {']
    for method_enum_name, method_off in methods:
        if method_off < 10:
            continue
        lines += [f'  TASK_METHOD_T {method_enum_name} = {method_off};']
    lines += [f'  TASK_METHOD_T kCount = {methods[-1][1] + 1};']
    lines += ['};', '', f'#endif  // {METHOD_MACRO}']
    with open(METHODS_H, 'w') as fp:
        fp.write('\n'.join(lines))


    # Produce the TASK_NAME_lib_exec.h file
    lines = []
    lines += [f'#ifndef {LIB_EXEC_MACRO}',
              f'#define {LIB_EXEC_MACRO}',
              '']
    ## Create the Run method
    lines += ['/** Execute a task */',
              'void Run(u32 method, Task *task, RunContext &rctx) override {',
              '  switch (method) {']
    for method_enum_name, method_off in methods:
        if method_off < 0:
            continue
        method_name = method_enum_name.replace('k', '', 1)
        task_name = method_name + "Task"
        lines += [f'    case Method::{method_enum_name}: {{',
                  f'      {method_name}(reinterpret_cast<{task_name} *>(task), rctx);',
                  f'      break;',
                  f'    }}']
    lines += ['  }']
    lines += ['}']

    ## Create the Monitor method
    lines += ['/** Execute a task */',
              'void Monitor(MonitorModeId mode, MethodId method, Task *task, RunContext &rctx) override {',
              '  switch (method) {']
    for method_enum_name, method_off in methods:
        if method_off < 0:
            continue
        method_name = method_enum_name.replace('k', '', 1)
        task_name = method_name + "Task"
        lines += [f'    case Method::{method_enum_name}: {{',
                  f'      Monitor{method_name}(mode, reinterpret_cast<{task_name} *>(task), rctx);',
                  f'      break;',
                  f'    }}']
    lines += ['  }']
    lines += ['}']

    ## Create the Del method
    lines += ['/** Delete a task */',
              'void Del(u32 method, Task *task) override {',
              '  switch (method) {']
    for method_enum_name, method_off in methods:
        if method_off < 0:
            continue
        method_name = method_enum_name.replace('k', '', 1)
        task_name = method_name + "Task"
        lines += [f'    case Method::{method_enum_name}: {{',
                  f'      CHI_CLIENT->DelTask<{task_name}>(reinterpret_cast<{task_name} *>(task));',
                  f'      break;',
                  f'    }}']
    lines += ['  }']
    lines += ['}']

    ## Create the CopyStart method
    lines += ['/** Duplicate a task */',
              'void CopyStart(u32 method, const Task *orig_task, Task *dup_task, bool deep) override {',
              '  switch (method) {']
    for method_enum_name, method_off in methods:
        if method_off < 0:
            continue
        method_name = method_enum_name.replace('k', '', 1)
        task_name = method_name + "Task"
        lines += [f'    case Method::{method_enum_name}: {{',
                  f'      chi::CALL_COPY_START(',
                  f'        reinterpret_cast<const {task_name}*>(orig_task), ',
                  f'        reinterpret_cast<{task_name}*>(dup_task), deep);',
                  f'      break;',
                  f'    }}']
    lines += ['  }']
    lines += ['}']

    ## Create the CopyStart method
    lines += ['/** Duplicate a task */',
              'void NewCopyStart(u32 method, const Task *orig_task, LPointer<Task> &dup_task, bool deep) override {',
              '  switch (method) {']
    for method_enum_name, method_off in methods:
        if method_off < 0:
            continue
        method_name = method_enum_name.replace('k', '', 1)
        task_name = method_name + "Task"
        lines += [f'    case Method::{method_enum_name}: {{',
                  f'      chi::CALL_NEW_COPY_START(reinterpret_cast<const {task_name}*>(orig_task), dup_task, deep);',
                  f'      break;',
                  f'    }}']
    lines += ['  }']
    lines += ['}']

    ## Create the SaveStart Method
    lines += ['/** Serialize a task when initially pushing into remote */',
              'void SaveStart(u32 method, BinaryOutputArchive<true> &ar, Task *task) override {',
              '  switch (method) {']
    for method_enum_name, method_off in methods:
        if method_off < 0:
            continue
        method_name = method_enum_name.replace('k', '', 1)
        task_name = method_name + "Task"
        lines += [f'    case Method::{method_enum_name}: {{',
                  f'      ar << *reinterpret_cast<{task_name}*>(task);',
                  f'      break;',
                  f'    }}']
    lines += ['  }']
    lines += ['}']

    ## Create the LoadStart Method
    lines += ['/** Deserialize a task when popping from remote queue */',
              'TaskPointer LoadStart(u32 method, BinaryInputArchive<true> &ar) override {',
              '  TaskPointer task_ptr;',
              '  switch (method) {']
    for method_enum_name, method_off in methods:
        if method_off < 0:
            continue
        method_name = method_enum_name.replace('k', '', 1)
        task_name = method_name + "Task"
        lines += [f'    case Method::{method_enum_name}: {{',
                  f'      task_ptr.ptr_ = CHI_CLIENT->NewEmptyTask<{task_name}>(task_ptr.shm_);',
                  f'      ar >> *reinterpret_cast<{task_name}*>(task_ptr.ptr_);',
                  f'      break;',
                  f'    }}']
    lines += ['  }']
    lines += ['  return task_ptr;']
    lines += ['}']

    ## Create the SaveEnd Method
    lines += ['/** Serialize a task when returning from remote queue */',
              'void SaveEnd(u32 method, BinaryOutputArchive<false> &ar, Task *task) override {',
              '  switch (method) {']
    for method_enum_name, method_off in methods:
        if method_off < 0:
            continue
        method_name = method_enum_name.replace('k', '', 1)
        task_name = method_name + "Task"
        lines += [f'    case Method::{method_enum_name}: {{',
                  f'      ar << *reinterpret_cast<{task_name}*>(task);',
                  f'      break;',
                  f'    }}']
    lines += ['  }']
    lines += ['}']

    ## Create the LoadEnd Method
    lines += ['/** Deserialize a task when popping from remote queue */',
              'void LoadEnd(u32 method, BinaryInputArchive<false> &ar, Task *task) override {',
              '  switch (method) {']
    for method_enum_name, method_off in methods:
        if method_off < 0:
            continue
        method_name = method_enum_name.replace('k', '', 1)
        task_name = method_name + "Task"
        lines += [f'    case Method::{method_enum_name}: {{',
                  f'      ar >> *reinterpret_cast<{task_name}*>(task);',
                  f'      break;',
                  f'    }}']
    lines += ['  }']
    lines += ['}']

    ## Finish the file
    lines += ['', f'#endif  // {METHOD_MACRO}']

    ## Write TASK_NAME_lib_exec.h
    with open(LIB_EXEC_H, 'w') as fp:
        fp.write('\n'.join(lines))

TASK_DIR = sys.argv[1]
TASK_ROOTS = [os.path.join(TASK_DIR, item) for item in os.listdir(TASK_DIR)]
for TASK_ROOT in TASK_ROOTS:
    try:
        refresh_methods(TASK_ROOT)
    except:
        pass
