#!/bin/bash
# Chimaera Runtime Container Entrypoint
# Generates runtime configuration and starts the Chimaera runtime daemon

set -e

# Load spack environment
source /opt/spack/share/spack/setup-env.sh
spack load iowarp@ai

echo "=== Chimaera Runtime Container Starting ==="
echo "Spack environment loaded: iowarp@ai"

# Function to parse size strings (e.g., "1G", "512M") to bytes
parse_size() {
    local size_str=$1
    local size_bytes=0

    # Check for G suffix (gigabytes)
    if [[ $size_str =~ ^([0-9]+)G$ ]]; then
        size_bytes=$((${BASH_REMATCH[1]} * 1024 * 1024 * 1024))
    # Check for M suffix (megabytes)
    elif [[ $size_str =~ ^([0-9]+)M$ ]]; then
        size_bytes=$((${BASH_REMATCH[1]} * 1024 * 1024))
    # Check for K suffix (kilobytes)
    elif [[ $size_str =~ ^([0-9]+)K$ ]]; then
        size_bytes=$((${BASH_REMATCH[1]} * 1024))
    # Assume bytes if no suffix
    elif [[ $size_str =~ ^([0-9]+)$ ]]; then
        size_bytes=${BASH_REMATCH[1]}
    else
        echo "ERROR: Invalid size format: $size_str"
        exit 1
    fi

    echo $size_bytes
}

# Parse size environment variables if they contain suffixes
if [[ $CHI_MAIN_SEGMENT_SIZE =~ [GMK]$ ]]; then
    CHI_MAIN_SEGMENT_SIZE=$(parse_size $CHI_MAIN_SEGMENT_SIZE)
fi
if [[ $CHI_CLIENT_DATA_SEGMENT_SIZE =~ [GMK]$ ]]; then
    CHI_CLIENT_DATA_SEGMENT_SIZE=$(parse_size $CHI_CLIENT_DATA_SEGMENT_SIZE)
fi
if [[ $CHI_RUNTIME_DATA_SEGMENT_SIZE =~ [GMK]$ ]]; then
    CHI_RUNTIME_DATA_SEGMENT_SIZE=$(parse_size $CHI_RUNTIME_DATA_SEGMENT_SIZE)
fi

# If custom config file is not provided, generate one from environment variables
if [ ! -f "$CHI_SERVER_CONF" ]; then
    echo "Generating Chimaera configuration at: $CHI_SERVER_CONF"

    cat > "$CHI_SERVER_CONF" <<EOF
# Chimaera Runtime Configuration
# Generated by Chimaera Docker Container

# Worker thread configuration
workers:
  sched_threads: ${CHI_SCHED_WORKERS}
  process_reaper_threads: ${CHI_PROCESS_REAPER_WORKERS}

# Memory segment configuration
memory:
  main_segment_size: ${CHI_MAIN_SEGMENT_SIZE}
  client_data_segment_size: ${CHI_CLIENT_DATA_SEGMENT_SIZE}
  runtime_data_segment_size: ${CHI_RUNTIME_DATA_SEGMENT_SIZE}

# Network configuration
network:
  zmq_port: ${CHI_ZMQ_PORT}

# Logging configuration
logging:
  level: "${CHI_LOG_LEVEL}"
  file: "/var/log/chimaera/chimaera.log"

# Performance tuning
performance:
  stack_size: ${CHI_STACK_SIZE}
  queue_depth: ${CHI_QUEUE_DEPTH}
  lane_map_policy: "round_robin"

# Shared memory configuration
shared_memory:
  main_segment_name: "chi_main_segment_\${USER}"
  client_data_segment_name: "chi_client_data_segment_\${USER}"
  runtime_data_segment_name: "chi_runtime_data_segment_\${USER}"

# Runtime configuration
runtime:
  heartbeat_interval: ${CHI_HEARTBEAT_INTERVAL}
  task_timeout: ${CHI_TASK_TIMEOUT}
EOF
else
    echo "Using provided configuration file: $CHI_SERVER_CONF"
fi

# Process hostfile if provided
if [ -n "$CHI_HOSTFILE" ]; then
    if [ -f "$CHI_HOSTFILE" ]; then
        echo "Using hostfile: $CHI_HOSTFILE"
        export CHI_HOSTFILE="$CHI_HOSTFILE"

        # Display hostfile contents
        echo "Hosts in cluster:"
        cat "$CHI_HOSTFILE"
    else
        echo "WARNING: CHI_HOSTFILE specified but file not found: $CHI_HOSTFILE"
    fi
fi

# Display configuration summary
echo ""
echo "=== Configuration Summary ==="
echo "Config file: $CHI_SERVER_CONF"
echo "Scheduler workers: $CHI_SCHED_WORKERS"
echo "Main segment size: $CHI_MAIN_SEGMENT_SIZE bytes"
echo "Client data segment size: $CHI_CLIENT_DATA_SEGMENT_SIZE bytes"
echo "Runtime data segment size: $CHI_RUNTIME_DATA_SEGMENT_SIZE bytes"
echo "ZeroMQ port: $CHI_ZMQ_PORT"
echo "Log level: $CHI_LOG_LEVEL"
echo "Shared memory size: $CHI_SHM_SIZE bytes"
echo ""

# Verify shared memory size is sufficient
TOTAL_SEGMENT_SIZE=$((CHI_MAIN_SEGMENT_SIZE + CHI_CLIENT_DATA_SEGMENT_SIZE + CHI_RUNTIME_DATA_SEGMENT_SIZE))
if [ $TOTAL_SEGMENT_SIZE -gt $CHI_SHM_SIZE ]; then
    echo "ERROR: Total segment size ($TOTAL_SEGMENT_SIZE bytes) exceeds shared memory size ($CHI_SHM_SIZE bytes)"
    echo "Increase CHI_SHM_SIZE or use --shm-size docker flag"
    exit 1
fi

# Check shared memory availability
SHM_AVAILABLE=$(df -B1 /dev/shm | tail -1 | awk '{print $4}')
echo "Shared memory available: $SHM_AVAILABLE bytes"
if [ $TOTAL_SEGMENT_SIZE -gt $SHM_AVAILABLE ]; then
    echo "WARNING: Total segment size ($TOTAL_SEGMENT_SIZE bytes) exceeds available shared memory ($SHM_AVAILABLE bytes)"
    echo "Container may fail to start. Use --shm-size flag to increase shared memory."
fi

# Export CHI_SERVER_CONF for chimaera_start_runtime
export CHI_SERVER_CONF

echo ""
echo "=== Starting Chimaera Runtime ==="
echo "Command: $@"
echo ""

# Execute the provided command (default: chimaera_start_runtime)
# The runtime will read CHI_SERVER_CONF from the environment
exec "$@"
