/**
 * Auto-generated execution implementation for MOD_NAME ChiMod
 * Implements Container virtual APIs directly using switch-case dispatch
 * 
 * This file is autogenerated - do not edit manually.
 * Changes should be made to the autogen tool or the YAML configuration.
 */

#include "chimaera/MOD_NAME/MOD_NAME_runtime.h"
#include "chimaera/MOD_NAME/autogen/MOD_NAME_methods.h"
#include <chimaera/chimaera.h>

namespace chimaera::MOD_NAME {

//==============================================================================
// Container Virtual API Implementations
//==============================================================================

void Runtime::Run(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr, chi::RunContext& rctx) {
  switch (method) {
    case Method::kCreate: {
      Create(task_ptr.Cast<CreateTask>(), rctx);
      break;
    }
    case Method::kDestroy: {
      Destroy(task_ptr.Cast<DestroyTask>(), rctx);
      break;
    }
    case Method::kCustom: {
      Custom(task_ptr.Cast<CustomTask>(), rctx);
      break;
    }
    case Method::kCoMutexTest: {
      CoMutexTest(task_ptr.Cast<CoMutexTestTask>(), rctx);
      break;
    }
    case Method::kCoRwLockTest: {
      CoRwLockTest(task_ptr.Cast<CoRwLockTestTask>(), rctx);
      break;
    }
    case Method::kFireAndForgetTest: {
      FireAndForgetTest(task_ptr.Cast<FireAndForgetTestTask>(), rctx);
      break;
    }
    case Method::kWaitTest: {
      WaitTest(task_ptr.Cast<WaitTestTask>(), rctx);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::Monitor(chi::MonitorModeId mode, chi::u32 method, 
                       hipc::FullPtr<chi::Task> task_ptr, chi::RunContext& rctx) {
  switch (method) {
    case Method::kCreate: {
      MonitorCreate(mode, task_ptr.Cast<CreateTask>(), rctx);
      break;
    }
    case Method::kDestroy: {
      MonitorDestroy(mode, task_ptr.Cast<DestroyTask>(), rctx);
      break;
    }
    case Method::kCustom: {
      MonitorCustom(mode, task_ptr.Cast<CustomTask>(), rctx);
      break;
    }
    case Method::kCoMutexTest: {
      MonitorCoMutexTest(mode, task_ptr.Cast<CoMutexTestTask>(), rctx);
      break;
    }
    case Method::kCoRwLockTest: {
      MonitorCoRwLockTest(mode, task_ptr.Cast<CoRwLockTestTask>(), rctx);
      break;
    }
    case Method::kFireAndForgetTest: {
      MonitorFireAndForgetTest(mode, task_ptr.Cast<FireAndForgetTestTask>(), rctx);
      break;
    }
    case Method::kWaitTest: {
      MonitorWaitTest(mode, task_ptr.Cast<WaitTestTask>(), rctx);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::Del(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr) {
  // Use IPC manager to deallocate task from shared memory
  auto* ipc_manager = CHI_IPC;
  
  switch (method) {
    case Method::kCreate: {
      ipc_manager->DelTask(task_ptr.Cast<CreateTask>());
      break;
    }
    case Method::kDestroy: {
      ipc_manager->DelTask(task_ptr.Cast<DestroyTask>());
      break;
    }
    case Method::kCustom: {
      ipc_manager->DelTask(task_ptr.Cast<CustomTask>());
      break;
    }
    case Method::kCoMutexTest: {
      ipc_manager->DelTask(task_ptr.Cast<CoMutexTestTask>());
      break;
    }
    case Method::kCoRwLockTest: {
      ipc_manager->DelTask(task_ptr.Cast<CoRwLockTestTask>());
      break;
    }
    case Method::kFireAndForgetTest: {
      ipc_manager->DelTask(task_ptr.Cast<FireAndForgetTestTask>());
      break;
    }
    case Method::kWaitTest: {
      ipc_manager->DelTask(task_ptr.Cast<WaitTestTask>());
      break;
    }
    default: {
      // For unknown methods, still try to delete from main segment
      ipc_manager->DelTask(task_ptr);
      break;
    }
  }
}

void Runtime::SaveIn(chi::u32 method, chi::TaskSaveInArchive& archive, 
                      hipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.Cast<CreateTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.Cast<DestroyTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kCustom: {
      auto typed_task = task_ptr.Cast<CustomTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kCoMutexTest: {
      auto typed_task = task_ptr.Cast<CoMutexTestTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kCoRwLockTest: {
      auto typed_task = task_ptr.Cast<CoRwLockTestTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kFireAndForgetTest: {
      auto typed_task = task_ptr.Cast<FireAndForgetTestTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kWaitTest: {
      auto typed_task = task_ptr.Cast<WaitTestTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::LoadIn(chi::u32 method, chi::TaskLoadInArchive& archive, 
                      hipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.Cast<CreateTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.Cast<DestroyTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kCustom: {
      auto typed_task = task_ptr.Cast<CustomTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kCoMutexTest: {
      auto typed_task = task_ptr.Cast<CoMutexTestTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kCoRwLockTest: {
      auto typed_task = task_ptr.Cast<CoRwLockTestTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kFireAndForgetTest: {
      auto typed_task = task_ptr.Cast<FireAndForgetTestTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    case Method::kWaitTest: {
      auto typed_task = task_ptr.Cast<WaitTestTask>();
      typed_task->SerializeIn(archive);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::SaveOut(chi::u32 method, chi::TaskSaveOutArchive& archive, 
                       hipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.Cast<CreateTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.Cast<DestroyTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kCustom: {
      auto typed_task = task_ptr.Cast<CustomTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kCoMutexTest: {
      auto typed_task = task_ptr.Cast<CoMutexTestTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kCoRwLockTest: {
      auto typed_task = task_ptr.Cast<CoRwLockTestTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kFireAndForgetTest: {
      auto typed_task = task_ptr.Cast<FireAndForgetTestTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kWaitTest: {
      auto typed_task = task_ptr.Cast<WaitTestTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::LoadOut(chi::u32 method, chi::TaskLoadOutArchive& archive, 
                       hipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.Cast<CreateTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.Cast<DestroyTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kCustom: {
      auto typed_task = task_ptr.Cast<CustomTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kCoMutexTest: {
      auto typed_task = task_ptr.Cast<CoMutexTestTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kCoRwLockTest: {
      auto typed_task = task_ptr.Cast<CoRwLockTestTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kFireAndForgetTest: {
      auto typed_task = task_ptr.Cast<FireAndForgetTestTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    case Method::kWaitTest: {
      auto typed_task = task_ptr.Cast<WaitTestTask>();
      typed_task->SerializeOut(archive);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::NewCopy(chi::u32 method, const hipc::FullPtr<chi::Task>& orig_task,
                       hipc::FullPtr<chi::Task>& dup_task, bool deep) {
  auto* ipc_manager = CHI_IPC;
  if (!ipc_manager) {
    return;
  }
  
  switch (method) {
    case Method::kCreate: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<CreateTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<CreateTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kDestroy: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<DestroyTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<DestroyTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kCustom: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<CustomTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<CustomTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kCoMutexTest: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<CoMutexTestTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<CoMutexTestTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kCoRwLockTest: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<CoRwLockTestTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<CoRwLockTestTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kFireAndForgetTest: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<FireAndForgetTestTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<FireAndForgetTestTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kWaitTest: {
      // Allocate new task using SHM default constructor
      auto typed_task = ipc_manager->NewTask<WaitTestTask>();
      if (!typed_task.IsNull()) {
        // Use HSHM strong copy method for actual copying
        typed_task->shm_strong_copy_main(*orig_task.Cast<WaitTestTask>());
        // Cast to base Task type for return
        dup_task = typed_task.template Cast<chi::Task>();
      }
      break;
    }
    default: {
      // For unknown methods, create base Task copy
      auto typed_task = ipc_manager->NewTask<chi::Task>();
      if (!typed_task.IsNull()) {
        typed_task->shm_strong_copy_main(*orig_task);
        dup_task = typed_task;  // Already chi::Task type
      }
      break;
    }
  }
  
  (void)deep;    // Deep copy parameter reserved for future use
}

} // namespace chimaera::MOD_NAME
